# 12 - Add Legacy SPO Permissions to Target User
# Reads the site permissions report generated by script 10 and grants the same
# permissions to the target/guest account in each site.
#
# Requires: Microsoft.Graph, PnP.PowerShell
# CSV columns: SourceUpn, TargetUpn
#
# Known issue: PnP.PowerShell loads an older Graph DLL that may conflict with
# Microsoft.Graph modules. If you get a type-load error on Get-MgUser, kill all
# PowerShell processes and reconnect Graph before running PnP commands.

# ---- CONFIGURATION ----
$tenantName           = "contoso.onmicrosoft.com"
$adminUrl             = "https://contoso-admin.sharepoint.com"
$pnpClientId          = "YOUR-PNP-CLIENT-ID"
$csvPath              = "C:\Temp\users.csv"
$permissionsReportPath = "C:\Temp\SpoSitePermissionsReport.csv"
# -----------------------

Import-Module Microsoft.Graph.Authentication
Import-Module Microsoft.Graph.Users
Import-Module PnP.PowerShell

Connect-MgGraph -TenantId $tenantName
$pnpConnection = Connect-PnPOnline -Url $adminUrl -Interactive -ReturnConnection -ClientId $pnpClientId

$SpoSitePermissionReport = Import-Csv $permissionsReportPath -Delimiter ";" -Encoding Unicode
$CsvUsers = Import-Csv $csvPath -Delimiter ";"

foreach ($user in $CsvUsers) {
    $sourceUpn = $user.SourceUpn
    $targetUpn = $user.TargetUpn

    $spo = $SpoSitePermissionReport | Where-Object { $_.Email -eq $sourceUpn }

    if ($spo) {
        Write-Host $sourceUpn -ForegroundColor DarkYellow

        $sourceUser = Get-MgUser -UserId $sourceUpn
        $targetUser = Get-MgUser -UserId $targetUpn

        if ($sourceUser -and $targetUser) {
            foreach ($site in $spo) {
                Connect-PnPOnline -Url $site.Url -Connection $pnpConnection -Interactive

                if ($site.Permission -eq "siteAdmin") {
                    Write-Host " Adding -> siteAdmin at $($site.Url) to $($targetUser.UserPrincipalName)"
                    # Comment out the line below for a dry run
                    Set-PnPTenantSite -Identity $site.Url -Owners $targetUser.UserPrincipalName
                }
                elseif ($site.GroupName -ne "") {
                    Write-Host " Adding -> $($site.Permission) at $($site.Url) to $($targetUser.UserPrincipalName) ($($site.GroupName))"
                    # Comment out the line below for a dry run
                    Add-PnPGroupMember -LoginName $targetUser.UserPrincipalName -Identity $site.GroupName
                }
            }
        }
        else {
            Write-Host "Could not retrieve user object for $sourceUpn / $targetUpn" -ForegroundColor White -BackgroundColor Red
        }
    }
    else {
        Write-Host "No legacy SPO permissions for $sourceUpn" -ForegroundColor DarkGray
    }
}
