# 34 - Remove Legacy SPO Permissions from Source User
# Uses the permissions report generated by script 10 to remove the source user's
# direct SharePoint site permissions. Run after script 12 has mirrored them to the target.
#
# Requires: Microsoft.Graph, PnP.PowerShell
# CSV columns: SourceUpn, TargetUpn

# ---- CONFIGURATION ----
$tenantName            = "contoso.onmicrosoft.com"
$adminUrl              = "https://contoso-admin.sharepoint.com"
$pnpClientId           = "YOUR-PNP-CLIENT-ID"
$csvPath               = "C:\Temp\users.csv"
$permissionsReportPath = "C:\Temp\SpoSitePermissionsReport.csv"
# -----------------------

Import-Module PnP.PowerShell

$SpoSitePermissionReport = Import-Csv $permissionsReportPath -Delimiter "," -Encoding Unicode
$CsvUsers = Import-Csv $csvPath -Delimiter ","

Connect-MgGraph -TenantId $tenantName
$pnpConnection = Connect-PnPOnline -Url $adminUrl -Interactive -ReturnConnection -ClientId $pnpClientId

foreach ($user in $CsvUsers) {
    $sourceUpn = $user.SourceUpn
    $targetUpn = $user.TargetUpn

    $spo = $SpoSitePermissionReport | Where-Object { $_.Email -eq $sourceUpn }

    if ($spo) {
        Write-Host $sourceUpn -ForegroundColor DarkYellow

        $sourceUser = Get-MgUser -UserId $sourceUpn
        $targetUser = Get-MgUser -UserId $targetUpn

        if ($sourceUser -and $targetUser) {
            foreach ($site in $spo) {
                Connect-PnPOnline -Url $site.Url -Connection $pnpConnection -Interactive

                if ($site.Permission -eq "siteAdmin") {
                    Write-Host "  -> Remove siteAdmin at $($site.Url) for $($sourceUser.UserPrincipalName)"
                    # Comment out the line below for a dry run
                    Remove-PnPSiteCollectionAdmin -Owners $sourceUser.UserPrincipalName
                }
                elseif ($site.GroupName -ne "") {
                    Write-Host "  -> Remove $($site.Permission) at $($site.Url) for $($sourceUser.UserPrincipalName) ($($site.GroupName))"
                    # Comment out the line below for a dry run
                    Remove-PnPGroupMember -LoginName $sourceUser.UserPrincipalName -Identity $site.GroupName
                }
            }
        }
        else {
            Write-Host "Could not retrieve user object for $sourceUpn / $targetUpn" -ForegroundColor White -BackgroundColor Red
        }
    }
    else {
        Write-Host "No legacy SPO permissions for $sourceUpn" -ForegroundColor DarkGray
    }
}

$DateAndTime = Get-Date -Format "yyyy-MM-dd_HH.mm"
$report | Export-Csv "C:\Temp\SpoSitePermissionsReport-$DateAndTime.csv" -Delimiter ";" -NoTypeInformation -Encoding Unicode
